### ISSUE TITLE
Input our own ROI locations

### ISSUE THREAD

**Issue by LindseyWiser** [PandoraMission/pandora-sim#10]
For commissioning, it would be useful if we could input our own ROI locations in VisibleSim instead of using the standard ROI selection function.

**Comment by christinahedges** [comment]
The way to do this right now is to just overwrite the `ROI_corners` attribute of the visible simulation with a list of corners for the ROIs.

e.g.
```
        vsim.ROI_corners
```

**Comment by LindseyWiser** [comment]
Got it! Thank you! 

For the ROI sizes (just commenting here since the other issue is closed), I'm able to set an ROI size when initializing the sim, but when calling sim.observe(), I get this error at the line Tom indicated: "ValueError: cannot reshape array of size 838860800 into shape (1,200,1,50,50)". Is there an easy fix for that? 

Appreciate the help!

**Comment by christinahedges** [comment]
@LindseyWiser you need to post an example of your code so I can help you. Make sure it's a Minimal Working Example (MWE) of the behavior
