### ISSUE TITLE
ROI size appears hardcoded, error on sim.observe()

### ISSUE THREAD

**Issue by LindseyWiser** [PandoraMission/pandora-sim#11]
(My apologies for the confusing Github etiquette when I bought this up in a different issue thread. I'll try to be clearer in the future!)

The issue: I specify a custom ROI size when I initialize VisibleSim(), but I then get an error when I call sim.observe(). The following code should reproduce the error: 

```
import pandorasat as ps
import pandorasim as pp
ps.utils.get_phoenix_model(teff=7000, jmag=10)
from pandorasim import VisibleSim, NIRSim
import astropy.units as u
from astropy.coordinates import SkyCoord

c = SkyCoord.from_name("K2-18")

sim = VisibleSim(nROIs=1, ROI_size=(200, 200)) 
sim.point(c.ra, c.dec, 0.*u.deg)

data = sim.observe(output_type="array")
```

The error I get is "ValueError: cannot reshape array of size 20000000 into shape (1,100,5,50,50)" at the following line in visiblesim.py: 
`data = data.reshape((self.nROIs, nframes, nr, 50, 50)).sum(axis=2)`

**Comment by christinahedges** [comment]
Hi @LindseyWiser thanks for opening the issue and providing a working code, I see there is an errant hard coded ROI size in the code. I've fixed it and released a new patch, please upgrade to `v1.0.10` for the fix on this! I'll leave the issue open for now, if you have any more problems with that patch or it doesn't fix it drop me a note here!

**Comment by DextersLabASU** [comment]
It works! Thanks!

**Comment by LindseyWiser** [comment]
This works! Thanks!
